kit-sdq/programming-lecture-eclipse-artemis

bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/mappings/ArtemisCourse.java
bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/mappings/ArtemisExercise.java
bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/mappings/ArtemisSubmission.java
bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/mappings/ParticipationDummy.java
bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/mappings/ResultsDummy.java
bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/mappings/exam/ArtemisExam.java
bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/rest/ArtemisRESTClient.java
testPlugin_activateByShortcut/src/testplugin_activateByShortcut/ShortcutHandler.java
testPlugin_activateByShortcut/src/testplugin_activateByShortcut/testConfig/LockAndSubmitTest.java

Change deserialization to using objectmapper, where possible.

Change deserialization

---

bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/git/GitHandler.java
bundles/edu.kit.kastel.sdq.eclipse.grading.core/src/edu/kit/kastel/sdq/eclipse/grading/core/ArtemisController.java

Small fixes with your commit-code.
Iff `commit.gpgsign=true` is set in the `.gitconfig` the commits won't work because JGit cannot sign them.
Also the e-mail-addresses had commas instead of periods.

`Bugfix` Fixed email-addresses and disabled commit-signing

---

.github/workflows/maven.yml
.github/workflows/products.yml
.github/workflows/spotless.yml
.github/workflows/updatesite.yml
bundles/edu.kit.kastel.sdq.eclipse.common.api/.classpath
bundles/edu.kit.kastel.sdq.eclipse.common.api/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.common.client/.classpath
bundles/edu.kit.kastel.sdq.eclipse.common.client/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.common.core/.classpath
bundles/edu.kit.kastel.sdq.eclipse.common.core/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.common.view/.classpath
bundles/edu.kit.kastel.sdq.eclipse.common.view/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.grading.view/.classpath
bundles/edu.kit.kastel.sdq.eclipse.grading.view/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.student.view/.classpath
bundles/edu.kit.kastel.sdq.eclipse.student.view/META-INF/MANIFEST.MF
jvm/feature/feature.xml
jvm/feature/pom.xml
jvm/linux/META-INF/MANIFEST.MF
jvm/linux/pom.xml
jvm/pom.xml
jvm/windows/META-INF/MANIFEST.MF
jvm/windows/pom.xml
pom.xml
releng/edu.kit.kastel.sdq.eclipse.grading.product/META-INF/MANIFEST.MF
releng/edu.kit.kastel.sdq.eclipse.grading.product/edu.kit.kastel.sdq.eclipse.grading.product
releng/edu.kit.kastel.sdq.eclipse.student.product/META-INF/MANIFEST.MF
releng/edu.kit.kastel.sdq.eclipse.student.product/edu.kit.kastel.sdq.eclipse.student.product

We'll have to decide when we'll do the update :)

Update to JDK 17 & Eclipse 2021-12

---

bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/sdq/eclipse/grading/client/git/GitHandler.java

Commit shall delete deleted files now. Fixes #175

Bugfix: Deleted files are not removed from remote on submit

---

bundles/edu.kit.kastel.sdq.eclipse.student.view/src/edu/kit/kastel/eclipse/student/view/ui/ArtemisStudentView.java

Just some OCD-thing but in the grading-edition we decided to sort the exercises alphabetically, so this should also be done in the student-edition for consistency.

Added alphabetical order for exercises in student-edition

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/sdq/eclipse/common/api/PreferenceConstants.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/sdq/eclipse/common/core/ExerciseArtemisController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/sdq/eclipse/common/core/GradingSystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/sdq/eclipse/common/core/StudentSystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/sdq/eclipse/common/core/SystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/preferences/ArtemisGradingPreferencesPage.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/preferences/PreferenceInitializer.java

Fixes #194 
@Shirkanesi does this work for you?
https://github.com/kit-sdq/programming-lecture-eclipse-artemis/actions/runs/2191268198

Added possibility for tokens (needed for 2FA enabled) to clone from git

---

bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/ui/TestDetailsDialog.java

Should fix partly #193: https://github.com/kit-sdq/programming-lecture-eclipse-artemis/issues/193#issuecomment-1106109726 (worked in a test-VM; not tested on bare-metal Linux)
EDIT: I will remove the link to the issue. Otherwise, it will be closed during the merge.

Fixed TestDetailsDialog

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/sdq/eclipse/common/api/PreferenceConstants.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/activator/CommonActivator.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/AdvancedPreferences.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/PreferenceInitializer.java

Resolves the part of https://github.com/kit-sdq/programming-lecture-eclipse-artemis/issues/193#issuecomment-1102993909

Added option to tweak preferences via Plugin

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/EclipseArtemisConstants.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/activator/CommonActivator.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/org/eclipse/wb/swt/ResourceManager.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/org/eclipse/wb/swt/SWTResourceManager.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/ArtemisGradingView.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/AssessmentTabComposite.java
bundles/edu.kit.kastel.sdq.eclipse.student.view/src/edu/kit/kastel/eclipse/student/view/ui/ArtemisStudentView.java

Help Buttons that link to the Docs Pages

Added help buttons to UI

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/artemis/AssessmentResult.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/artemis/mapping/ResultsDTO.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/artemis/AnnotationMapper.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/ui/AbstractResultTab.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/ui/AbstractResultTabCompositeController.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/ResultTab.java
bundles/edu.kit.kastel.sdq.eclipse.student.view/src/edu/kit/kastel/eclipse/student/view/ui/ResultTab.java

See https://github.com/ls1intum/Artemis/pull/5175

Remove deprecated Result String

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/PreferenceConstants.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/artemis/mapping/User.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/client/IAuthenticationArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/controller/IArtemisController.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/META-INF/MANIFEST.MF
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/BrowserLogin.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/git/GitHandler.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/AbstractArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/LoginManager.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/RestClientManager.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/ArtemisController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/ExerciseArtemisController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/GradingSystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/StudentSystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/SystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/AdvancedPreferences.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/ArtemisPreferencesPage.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/PreferenceInitializer.java

Resolves #244 
Provides a login via Browser. It takes the JWT Token upon successful login. Thereby, we are independent from the login technology.
Tested on Windows 11 and Ubuntu 20.04.
Needs to be tested on 
See https://github.com/ls1intum/Artemis/pull/5216

Implementation of Login Workflow

---

bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/artemis/WorkspaceUtil.java

The build commands were incomplete. Therefore, students could not execute the programs after cloning

Add build commands to imported project

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/artemis/mapping/IExercise.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/mappings/ArtemisExercise.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/StudentSystemwideController.java

Properly handle start dates: https://github.com/ls1intum/Artemis/pull/5816
Implement start date handling for students.

Add StartDate functionality

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/client/IAssessmentArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/controller/ExerciseStats.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/controller/IGradingArtemisController.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/controller/IGradingSystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/mappings/stats/Stats.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/mappings/stats/Timing.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/AssessmentArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/SubmissionsArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/GradingArtemisController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/GradingSystemwideController.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/GermanLanguage.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/I18N.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/ArtemisGradingView.java

Closes #269
See #269
Use the API of Artemis to retrieve stats

Statistics for Assessment

---

docs/grading/grading.dev.rst
pom.xml

Bump versions to current release of eclipse

Eclipse 2022-12

---

docs/Home.md

This Pull request addresses issue #300

Added AUR Package to the documentation

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/artemis/mapping/Feedback.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/artemis/mapping/FeedbackType.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/controller/IAssessmentController.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/model/IMistakeType.java
bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/model/IRatingGroup.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/AssessmentController.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/artemis/AnnotationDeserializer.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/artemis/AnnotationMapper.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/config/ExerciseConfigConverter.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/model/MistakeType.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/model/RatingGroup.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/model/annotation/Annotation.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/model/rule/PenaltyRule.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/GermanLanguage.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/I18N.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/utilities/AssessmentUtilities.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/ArtemisGradingView.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/AutograderUtil.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/commands/AddAnnotationCommandHandler.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/commands/AddAnnotationDialog.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/commands/AnnotationFilter.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/controllers/AssessmentViewController.java
docs/Home.md
docs/examples/config.json

This PR adds the ability to view the buttons for grading in multiple languages (this does not effect the data sent to Artemis)
Use different language settings and save and load gradings.

Multi Language for Buttons

---

bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/AutograderUtil.java

The autograder should not add annotations for disabled buttons -> #310 
/cc @Feuermagier

Feature: Skip Autograder annotations if button is disabled

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/EclipseArtemisConstants.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/AbstractArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/AssessmentArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/FeedbackArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/LoginManager.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/ParticipationArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/SubmissionsArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/eclipse/common/client/rest/UtilArtemisClient.java
bundles/edu.kit.kastel.sdq.eclipse.common.core/src/edu/kit/kastel/eclipse/common/core/GradingArtemisController.java

⚠️ Breaking Change of Artemis API ⚠️ 
See https://github.com/ls1intum/Artemis/pull/6165

`Feature`: Update to new endpoints

---

bundles/edu.kit.kastel.sdq.eclipse.common.api/src/edu/kit/kastel/eclipse/common/api/PreferenceConstants.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/AdvancedPreferences.java
bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/PreferenceInitializer.java
bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/AutograderUtil.java

Close #333
Toggle preference under Artemis > Advanced and run the autograder. No popup.

✨ disable autograder popup on successful run
